Update 5-is_the_host_on_the_network

diff --git a/0x07-networking_basics/5-is_the_host_on_the_network b/0x07-networking_basics/5-is_the_host_on_the_network
--- a/0x07-networking_basics/5-is_the_host_on_the_network
+++ b/0x07-networking_basics/5-is_the_host_on_the_network
@@ -1,13 +1,20 @@
 #!/bin/bash
 
-# Check if an argument is provided
+# Check if an argument has been provided
 if [ $# -eq 0 ]; then
-    echo "Usage: $0 {IP_ADDRESS}"
-    exit 1
+  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
+  exit 1
 fi
 
-# Extract the IP address from the argument
+# Retrieve the IP address from the first argument
 ip_address=$1
 
-# Ping the IP address 5 times and display the results
+# Ping the IP address 5 times
 ping -c 5 $ip_address
+
+# Check the exit status of the ping command
+if [ $? -eq 0 ]; then
+  echo "$ip_address is reachable."
+else
+  echo "$ip_address is unreachable."
+fi
